### PR TITLE
fix(composables): toggle relative url slash

### LINKED ISSUE #442: [BUG] Corrupted CmsElementImage url
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Configured CmsElementImage to have link type category in Admin Cms builder.
Screenshot from 2023-10-27 18-08-33

Url is passed to Fe with structure "/Namams/"

useCmsElementImage checks if url is absolute and if not, adds another "/" to the url start.
https://github.com/shopware/frontends/blob/main/packages/composables/src/cms/useCmsElementImage.ts#L61

Result:
Screenshot from 2023-10-27 18-13-06

Double // cancel each other out and browser redirects to url "namams" without domain after click.

### Expected Behavior

useCmsElementImage should check if url already have "/" at the starts, and only add it if its absent.

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mdanilowicz**
### Description

 closes #442 

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by BrocksiNet** [comment]
What is the difference to [this](https://github.com/shopware/frontends/commit/f636e5a648d2d13b83589b34e377f1d3fccc1cf7)?

Could this be unified?

**Comment by mdanilowicz** [comment]
> What is the difference to [this](https://github.com/shopware/frontends/commit/f636e5a648d2d13b83589b34e377f1d3fccc1cf7)?
> 
> Could this be unified?

Those are 2 different packages, we should not use composables helpers in the CMS package. I'm also not sure that we need the same helper there.

**Comment by mkucmus** [comment]
> > What is the difference to [this](https://github.com/shopware/frontends/commit/f636e5a648d2d13b83589b34e377f1d3fccc1cf7)?
> > Could this be unified?
> 
> Those are 2 different packages, we should not use composables helpers in the CMS package. I'm also not sure that we need the same helper there.

If there are two different packages, but the helper function's purpose is the same, please move the function to the shared package named `@shopware-pwa/helpers-next` and use it in two places

**Review by mkucmus — APPROVED** [review]
🥇

**Pull request merged**
