### PR TITLE
feat(cms-base): enable overriding the internal components

### PR DESCRIPTION
**Pull request by mkucmus**
### Description

closes: #354 

tl;dr: this change allows to overwrite also the internal components with a name starting with `Sw` from `cms-base` package.

### CODE REVIEW

**Comment by mkucmus** [comment]
@kstala please have a look if the change does not break the way how cms elements and blocks are rendered 🙌🏼

**Comment by kstala** [comment]
I checked all cms elements and apart from the well-known issue with [ CmsBlockImageGalleryBig](https://github.com/shopware/frontends/issues/1306), everything looks correct

**Review by kstala — APPROVED** [review]

**Comment by BrocksiNet** [comment]
Will we close that without merging?

**Comment by mkucmus** [comment]
> Will we close that without merging?

it is still being reviewed, then the PR will close #354 and unblock a customer's project.

**Review by patzick — APPROVED** [review]

**Pull request merged**
