### PR TITLE
chore(docs): Embed docs to DevHub

### PR DESCRIPTION
**Pull request by bojanrajh**
### Description

This PR cleans up this repo for embedding `frontends` info `developer-portal` - https://github.com/shopware/developer-portal/pull/128

### ToDo's

- [X] removed `@shopware-pwa/typer` private package, moved it to `@shopware-docs/typer` (now public/published)
- [X] cleaned up `apps/docs` folder
- [X] added shortcuts to `package.json` - `docs:env`, `docs:link` and `docs:preview`
- [X] added DevHub workflows for previewing and deploying changes
- [x] static sidebar
- [x] fixed deadlinks, added missing files
- [x] kept `package.json`
- [ ] set up `DEV_HUB_PERSONAL_ACCESS_TOKEN` secret
- [ ] deactivate Vercel integration

### CODE REVIEW

**Comment by BrocksiNet** [comment]
What is missing? Can we somehow support it? Asking for a friend.

**Comment by bojanrajh** [comment]
> What is missing? Can we somehow support it? Asking for a friend.

I'll rebase, sync the `typer` package, then we can talk about the _new_ docs workflow. You can still use your _old_ (isolated) and _new_ (embedded) workflows, and this branch is already published to [prod](https://developer.shopware.com/frontends/) (though not linked in the menu, it is searchable by Algolia and contents are provided to the Copilot AI).

**Comment by bojanrajh** [comment]
@BrocksiNet This was rebased, but generated API references are not working on prod because of the new plugin structure. We'll need to adapt that on our end.

**Comment by BrocksiNet** [comment]
> @BrocksiNet This was rebased, but generated API references are not working on prod because of the new plugin structure. We'll need to adapt that on our end.

Thx @bojanrajh :raised_hands: Great work.

We discussed updating our docs to the newest Vitepress version ([see](https://github.com/shopware/developer-documentation-vitepress/releases/tag/v1.1.41)).
Do you see any problem with that? :grinning:

**Comment by bojanrajh** [comment]
Technically, you could see changes in `theme.json` and `package.json` in this branch. You can also use clean version of `config.ts` (because config is already in `baseConfig` (and `sidebar.ts`). Keep your plugin definition and you should be good with your standalone docs.

This branch already includes the latest version, but there are 2 breaking changes: API reference (though, it should be properly generated in the standalone version, but not in the DevHub context) and local search (replaced with algolia). Along with possible minor CSS changes from past months (I did apply some stuff from this repo into the theme already).

**Comment by bojanrajh** [comment]
Closing in favour of https://github.com/shopware/frontends/pull/1313, https://github.com/shopware/frontends/pull/1327 and https://github.com/shopware/frontends/pull/1337.

**Pull request closed without merging**
